from typing import Union
from PySpice.Unit.Unit import UnitValue

def str_spice(obj: Union[UnitValue, str], unit: bool = ...) -> str: ...
def str_spice_list(*args) -> list[str]: ...
def join_dict(d: dict) -> str: ...
def join_lines(items, prefix='') -> str: ...
def join_list(items) -> str: ...
