from ..Tools.File import Directory as Directory
from .Parser import SpiceParser as SpiceParser
from _typeshed import Incomplete

class SpiceLibrary:
    EXTENSIONS: Incomplete
    def __init__(self, root_path, recurse: bool = ..., section: Incomplete | None = ...) -> None: ...
    def __getitem__(self, name): ...
    @property
    def subcircuits(self): ...
    @property
    def models(self): ...
    def search(self, s): ...
