from PySpice.Probe.WaveForm import AcAnalysis as AcAnalysis, DcAnalysis as DcAnalysis, OperatingPoint as OperatingPoint, SensitivityAnalysis as SensitivityAnalysis, TransientAnalysis as TransientAnalysis, WaveForm as WaveForm
from PySpice.Unit import u_A as u_A, u_Degree as u_Degree, u_Hz as u_Hz, u_V as u_V, u_s as u_s
from _typeshed import Incomplete

class VariableAbc:
    name: Incomplete
    data: Incomplete
    def __init__(self, index, name, unit) -> None: ...
    @property
    def index(self): ...
    def is_voltage_node(self) -> None: ...
    def is_branch_current(self) -> None: ...
    @property
    def is_interval_parameter(self): ...
    @staticmethod
    def to_voltage_name(node): ...
    @staticmethod
    def to_branch_name(element): ...
    def fix_case(self, element_translation, node_translation) -> None: ...
    @property
    def simplified_name(self) -> None: ...
    def to_waveform(self, abscissa: Incomplete | None = ..., to_real: bool = ..., to_float: bool = ...): ...

class RawFileAbc:
    @property
    def simulation(self): ...
    @property
    def circuit(self): ...
    def nodes(self, to_float: bool = ..., abscissa: Incomplete | None = ...): ...
    def branches(self, to_float: bool = ..., abscissa: Incomplete | None = ...): ...
    def internal_parameters(self, to_float: bool = ..., abscissa: Incomplete | None = ...): ...
    def elements(self, abscissa: Incomplete | None = ...): ...
    def to_analysis(self): ...
