from ..RawFile import RawFileAbc as RawFileAbc, VariableAbc as VariableAbc
from _typeshed import Incomplete

class Variable(VariableAbc):
    def is_voltage_node(self): ...
    def is_branch_current(self): ...
    @property
    def simplified_name(self): ...

class RawFile(RawFileAbc):
    number_of_points: Incomplete
    def __init__(self, stdout, number_of_points) -> None: ...
    def fix_case(self) -> None: ...
