from ..RawFile import RawFileAbc as RawFileAbc, VariableAbc as VariableAbc

class Variable(VariableAbc):
    def is_voltage_node(self): ...
    def is_branch_current(self): ...
    @staticmethod
    def to_voltage_name(node): ...
    @property
    def simplified_name(self): ...

class RawFile(RawFileAbc):
    def __init__(self, output) -> None: ...
    def fix_case(self) -> None: ...
