from _typeshed import Incomplete

class Manufacturer:
    def __init__(self, name, url: Incomplete | None = ...) -> None: ...
    @property
    def name(self): ...
    @property
    def url(self): ...

class Footprint:
    def __init__(self, name) -> None: ...
    @property
    def name(self): ...

class Device:
    def __init__(self, name, manufacturer, datasheet_url: Incomplete | None = ..., model_url: Incomplete | None = ...) -> None: ...
    @property
    def name(self): ...
