from _typeshed import Incomplete

class CircuitTest:
    def test_spinit(self) -> None: ...

class PySpicePostInstallation:
    GITHUB_URL: str
    NGSPICE_BASE_URL: str
    NGSPICE_RELEASE_URL: Incomplete
    NGSPICE_WINDOWS_DLL_URL: Incomplete
    NGSPICE_WINDOWS_DLL_OLD_URL: Incomplete
    NGSPICE_MANUAL_URL: Incomplete
    NGSPICE_MANUAL_OLD_URL: Incomplete
    def run(self) -> None: ...
    @property
    def ngspice_version(self): ...
    def install_ngspice_dll(self) -> None: ...
    def download_ngspice_manual(self) -> None: ...
    def check_installation(self) -> None: ...
    def download_example(self) -> None: ...

def main(): ...
