def bode_diagram_gain(axe, frequency, gain, **kwargs) -> None: ...
def bode_diagram_phase(axe, frequency, phase, **kwargs) -> None: ...
def bode_diagram(axes, frequency, gain, phase, **kwargs) -> None: ...
