from _typeshed import Incomplete

class ShockleyDiode:
    Is: Incomplete
    n: Incomplete
    T: Incomplete
    def __init__(self, Is: float = ..., n: int = ..., degree: int = ..., kelvin: Incomplete | None = ...) -> None: ...
    @property
    def Vt(self): ...
    def I(self, Vd): ...
    def rd(self, Vd): ...
