from typing import Any
from . import Unit as _Unit
from _typeshed import Incomplete

class UnitValueShorcut:
    _prefixed_unit: _Unit.PrefixedUnit
    def __init__(self, prefixed_unit: _Unit.PrefixedUnit) -> None: ...
    def __call__(self, other) -> _Unit.UnitValue: ...
    def __rmatmul__(self, other): ...

def define_shortcut(name, shortcut) -> None: ...

class FrequencyValue(_Unit.UnitValue, _Unit.FrequencyMixin): ...
class FrequencyValues(_Unit.UnitValues): ...
class PeriodValue(_Unit.UnitValue, _Unit.PeriodMixin): ...
class PeriodValues(_Unit.UnitValues): ...

def as_Degree(value: Any) -> _Unit.UnitValue: ...
def as_A(value: Any) -> _Unit.UnitValue: ...
def as_F(value: Any) -> _Unit.UnitValue: ...
def as_H(value: Any) -> _Unit.UnitValue: ...
def as_Hz(value: Any) -> FrequencyValue: ...
def as_V(value: Any) -> _Unit.UnitValue: ...
def as_m(value: Any) -> _Unit.UnitValue: ...
def as_s(value: Any) -> PeriodValue: ...
def as_Ω(value: Any) -> _Unit.UnitValue: ...
def as_Ohm(value: Any) -> _Unit.UnitValue: ...

U_TDegree: _Unit.PrefixedUnit = ...
U_GDegree: _Unit.PrefixedUnit = ...
U_MDegree: _Unit.PrefixedUnit = ...
U_kDegree: _Unit.PrefixedUnit = ...
U_Degree: _Unit.PrefixedUnit = ...
U_mDegree: _Unit.PrefixedUnit = ...
U_uDegree: _Unit.PrefixedUnit = ...
U_nDegree: _Unit.PrefixedUnit = ...
U_pDegree: _Unit.PrefixedUnit = ...
U_TA: _Unit.PrefixedUnit = ...
U_GA: _Unit.PrefixedUnit = ...
U_MA: _Unit.PrefixedUnit = ...
U_kA: _Unit.PrefixedUnit = ...
U_A: _Unit.PrefixedUnit = ...
U_mA: _Unit.PrefixedUnit = ...
U_μA: _Unit.PrefixedUnit = ...
U_uA: _Unit.PrefixedUnit = ...
U_nA: _Unit.PrefixedUnit = ...
U_pA: _Unit.PrefixedUnit = ...
U_TF: _Unit.PrefixedUnit = ...
U_GF: _Unit.PrefixedUnit = ...
U_MF: _Unit.PrefixedUnit = ...
U_kF: _Unit.PrefixedUnit = ...
U_F: _Unit.PrefixedUnit = ...
U_mF: _Unit.PrefixedUnit = ...
U_μF: _Unit.PrefixedUnit = ...
U_uF: _Unit.PrefixedUnit = ...
U_nF: _Unit.PrefixedUnit = ...
U_pF: _Unit.PrefixedUnit = ...
U_TH: _Unit.PrefixedUnit = ...
U_GH: _Unit.PrefixedUnit = ...
U_MH: _Unit.PrefixedUnit = ...
U_kH: _Unit.PrefixedUnit = ...
U_H: _Unit.PrefixedUnit = ...
U_mH: _Unit.PrefixedUnit = ...
U_μH: _Unit.PrefixedUnit = ...
U_uH: _Unit.PrefixedUnit = ...
U_nH: _Unit.PrefixedUnit = ...
U_pH: _Unit.PrefixedUnit = ...
U_THz: _Unit.PrefixedUnit = ...
U_GHz: _Unit.PrefixedUnit = ...
U_MHz: _Unit.PrefixedUnit = ...
U_kHz: _Unit.PrefixedUnit = ...
U_Hz: _Unit.PrefixedUnit = ...
U_mHz: _Unit.PrefixedUnit = ...
U_μHz: _Unit.PrefixedUnit = ...
U_uHz: _Unit.PrefixedUnit = ...
U_nHz: _Unit.PrefixedUnit = ...
U_pHz: _Unit.PrefixedUnit = ...
U_TV: _Unit.PrefixedUnit = ...
U_GV: _Unit.PrefixedUnit = ...
U_MV: _Unit.PrefixedUnit = ...
U_kV: _Unit.PrefixedUnit = ...
U_V: _Unit.PrefixedUnit = ...
U_mV: _Unit.PrefixedUnit = ...
U_μV: _Unit.PrefixedUnit = ...
U_uV: _Unit.PrefixedUnit = ...
U_nV: _Unit.PrefixedUnit = ...
U_pV: _Unit.PrefixedUnit = ...
U_Tm: _Unit.PrefixedUnit = ...
U_Gm: _Unit.PrefixedUnit = ...
U_Mm: _Unit.PrefixedUnit = ...
U_km: _Unit.PrefixedUnit = ...
U_m: _Unit.PrefixedUnit = ...
U_mm: _Unit.PrefixedUnit = ...
U_μm: _Unit.PrefixedUnit = ...
U_um: _Unit.PrefixedUnit = ...
U_nm: _Unit.PrefixedUnit = ...
U_pm: _Unit.PrefixedUnit = ...
U_Ts: _Unit.PrefixedUnit = ...
U_Gs: _Unit.PrefixedUnit = ...
U_Ms: _Unit.PrefixedUnit = ...
U_ks: _Unit.PrefixedUnit = ...
U_s: _Unit.PrefixedUnit = ...
U_ms: _Unit.PrefixedUnit = ...
U_μs: _Unit.PrefixedUnit = ...
U_us: _Unit.PrefixedUnit = ...
U_ns: _Unit.PrefixedUnit = ...
U_ps: _Unit.PrefixedUnit = ...
U_TΩ: _Unit.PrefixedUnit = ...
U_GΩ: _Unit.PrefixedUnit = ...
U_MΩ: _Unit.PrefixedUnit = ...
U_kΩ: _Unit.PrefixedUnit = ...
U_Ω: _Unit.PrefixedUnit = ...
U_mΩ: _Unit.PrefixedUnit = ...
U_μΩ: _Unit.PrefixedUnit = ...
U_nΩ: _Unit.PrefixedUnit = ...
U_pΩ: _Unit.PrefixedUnit = ...
U_TOhm: _Unit.PrefixedUnit = ...
U_GOhm: _Unit.PrefixedUnit = ...
U_MOhm: _Unit.PrefixedUnit = ...
U_kOhm: _Unit.PrefixedUnit = ...
U_Ohm: _Unit.PrefixedUnit = ...
U_mOhm: _Unit.PrefixedUnit = ...
U_uOhm: _Unit.PrefixedUnit = ...
U_nOhm: _Unit.PrefixedUnit = ...
U_pOhm: _Unit.PrefixedUnit = ...
u_TDegree: UnitValueShorcut = ...
u_GDegree: UnitValueShorcut = ...
u_MDegree: UnitValueShorcut = ...
u_kDegree: UnitValueShorcut = ...
u_Degree: UnitValueShorcut = ...
u_mDegree: UnitValueShorcut = ...
u_uDegree: UnitValueShorcut = ...
u_nDegree: UnitValueShorcut = ...
u_pDegree: UnitValueShorcut = ...
u_TA: UnitValueShorcut = ...
u_GA: UnitValueShorcut = ...
u_MA: UnitValueShorcut = ...
u_kA: UnitValueShorcut = ...
u_A: UnitValueShorcut = ...
u_mA: UnitValueShorcut = ...
u_μA: UnitValueShorcut = ...
u_uA: UnitValueShorcut = ...
u_nA: UnitValueShorcut = ...
u_pA: UnitValueShorcut = ...
u_TF: UnitValueShorcut = ...
u_GF: UnitValueShorcut = ...
u_MF: UnitValueShorcut = ...
u_kF: UnitValueShorcut = ...
u_F: UnitValueShorcut = ...
u_mF: UnitValueShorcut = ...
u_μF: UnitValueShorcut = ...
u_uF: UnitValueShorcut = ...
u_nF: UnitValueShorcut = ...
u_pF: UnitValueShorcut = ...
u_TH: UnitValueShorcut = ...
u_GH: UnitValueShorcut = ...
u_MH: UnitValueShorcut = ...
u_kH: UnitValueShorcut = ...
u_H: UnitValueShorcut = ...
u_mH: UnitValueShorcut = ...
u_μH: UnitValueShorcut = ...
u_uH: UnitValueShorcut = ...
u_nH: UnitValueShorcut = ...
u_pH: UnitValueShorcut = ...
u_THz: UnitValueShorcut = ...
u_GHz: UnitValueShorcut = ...
u_MHz: UnitValueShorcut = ...
u_kHz: UnitValueShorcut = ...
u_Hz: UnitValueShorcut = ...
u_mHz: UnitValueShorcut = ...
u_μHz: UnitValueShorcut = ...
u_uHz: UnitValueShorcut = ...
u_nHz: UnitValueShorcut = ...
u_pHz: UnitValueShorcut = ...
u_TV: UnitValueShorcut = ...
u_GV: UnitValueShorcut = ...
u_MV: UnitValueShorcut = ...
u_kV: UnitValueShorcut = ...
u_V: UnitValueShorcut = ...
u_mV: UnitValueShorcut = ...
u_μV: UnitValueShorcut = ...
u_uV: UnitValueShorcut = ...
u_nV: UnitValueShorcut = ...
u_pV: UnitValueShorcut = ...
u_Tm: UnitValueShorcut = ...
u_Gm: UnitValueShorcut = ...
u_Mm: UnitValueShorcut = ...
u_km: UnitValueShorcut = ...
u_m: UnitValueShorcut = ...
u_mm: UnitValueShorcut = ...
u_μm: UnitValueShorcut = ...
u_um: UnitValueShorcut = ...
u_nm: UnitValueShorcut = ...
u_pm: UnitValueShorcut = ...
u_Ts: UnitValueShorcut = ...
u_Gs: UnitValueShorcut = ...
u_Ms: UnitValueShorcut = ...
u_ks: UnitValueShorcut = ...
u_s: UnitValueShorcut = ...
u_ms: UnitValueShorcut = ...
u_μs: UnitValueShorcut = ...
u_us: UnitValueShorcut = ...
u_ns: UnitValueShorcut = ...
u_ps: UnitValueShorcut = ...
u_TΩ: UnitValueShorcut = ...
u_GΩ: UnitValueShorcut = ...
u_MΩ: UnitValueShorcut = ...
u_kΩ: UnitValueShorcut = ...
u_Ω: UnitValueShorcut = ...
u_mΩ: UnitValueShorcut = ...
u_μΩ: UnitValueShorcut = ...
u_nΩ: UnitValueShorcut = ...
u_pΩ: UnitValueShorcut = ...
u_TOhm: UnitValueShorcut = ...
u_GOhm: UnitValueShorcut = ...
u_MOhm: UnitValueShorcut = ...
u_kOhm: UnitValueShorcut = ...
u_Ohm: UnitValueShorcut = ...
u_mOhm: UnitValueShorcut = ...
u_uOhm: UnitValueShorcut = ...
u_nOhm: UnitValueShorcut = ...
u_pOhm: UnitValueShorcut = ...

unit_value: Incomplete
Frequency = u_Hz
Period = u_s
